export const ENV_PATH = '.env';
export const NODE_ENV = 'NODE_ENV';
export enum ENV_VARIABLES_NAMES {
  SSL_TLS = 'SSL_TLS',
  HOST = 'HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  USER = 'USER',
  PASSWORD = 'PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  MASK = 'MASK',
  ACCESS_JWT_PERIOD = 'ACCESS_JWT_PERIOD',
  REFRESH_JWT_PERIOD = 'REFRESH_JWT_PERIOD',
  DATABASE_URL = 'DATABASE_URL',
  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  ACCESS_TOKEN_EXPIRATION = 'ACCESS_TOKEN_EXPIRATION',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  REFRESH_TOKEN_EXPIRATION = 'REFRESH_TOKEN_EXPIRATION',
  COOKIE_HTTP_ONLY = 'COOKIE_HTTP_ONLY',
  COOKIE_PATH = 'COOKIE_PATH',
  COOKIE_MAX_AGE = 'COOKIE_MAX_AGE',
}

export enum STRATEGIES_NAMES {
  JWT = 'jwt',
  JWT_REFRESH = 'jwt-refresh',
  LOCAL = 'local',
}

export const DATABASE_TYPE = 'postgres';
export const PORT = 5000;
