USE Halaleenko_laba4

SELECT FACULTY.FACULTY AS ФАКУЛЬТЕТ, PULPIT.PULPIT_NAME AS КАФЕДРЫ, PROFESSION.PROFESSION_NAME AS ТЕХНОЛОГИЧЕСКИЕ_СПЕЦИАЛЬНОСТИ
	FROM FACULTY, PULPIT, PROFESSION
	WHERE FACULTY.FACULTY = PULPIT.FACULTY
	AND FACULTY.FACULTY = PROFESSION.FACULTY
	AND PROFESSION.PROFESSION_NAME IN(SELECT PROFESSION.PROFESSION_NAME 
		FROM PROFESSION 
		WHERE PROFESSION.PROFESSION_NAME LIKE '%технологи%');


SELECT FACULTY.FACULTY AS ФАКУЛЬТЕТ, PULPIT.PULPIT_NAME AS КАФЕДРЫ, PROFESSION.PROFESSION_NAME AS ТЕХНОЛОГИЧЕСКИЕ_СПЕЦИАЛЬНОСТИ
	FROM FACULTY
	INNER JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
	INNER JOIN PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
	WHERE PROFESSION_NAME IN(SELECT PROFESSION.PROFESSION_NAME 
		FROM PROFESSION 
		WHERE PROFESSION.PROFESSION_NAME LIKE '%технологи%');


SELECT FACULTY.FACULTY AS ФАКУЛЬТЕТ, PULPIT.PULPIT_NAME AS КАФЕДРЫ, PROFESSION.PROFESSION_NAME AS ТЕХНОЛОГИЧЕСКИЕ_СПЕЦИАЛЬНОСТИ
	FROM FACULTY
	INNER JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
	INNER JOIN PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
	WHERE (PROFESSION_NAME LIKE '%технологи%');


SELECT AUDITORIUM_TYPE AS ТИП_АУДИТОРИИ, AUDITORIUM_CAPACITY AS ВМЕСТИМОСТЬ 
	FROM AUDITORIUM A
	WHERE AUDITORIUM_CAPACITY IN (SELECT TOP(1) AUDITORIUM_CAPACITY 
	FROM AUDITORIUM B
	WHERE B.AUDITORIUM_TYPE = A.AUDITORIUM_TYPE
		ORDER BY AUDITORIUM_CAPACITY DESC);


SELECT FACULTY.FACULTY_NAME AS НАИМЕНОВАНИЕ_ФАКУЛЬТЕТА, PULPIT.PULPIT AS КАФЕДРA 
	FROM FACULTY, PULPIT
		WHERE  NOT EXISTS (SELECT * FROM PULPIT WHERE FACULTY.FACULTY = PULPIT.FACULTY)

SELECT FACULTY.FACULTY_NAME AS НАИМЕНОВАНИЕ_ФАКУЛЬТЕТА, PULPIT.PULPIT AS КАФЕДРА 
	FROM FACULTY, PULPIT
		WHERE EXISTS (SELECT * FROM PULPIT WHERE FACULTY.FACULTY = PULPIT.FACULTY)


SELECT TOP 1
	(SELECT avg(PROGRESS.NOTE) FROM PROGRESS
			WHERE PROGRESS.SUBJECT like 'ОАиП')  AS Средняя_по_ОАиП,
	(SELECT avg(PROGRESS.NOTE) FROM PROGRESS
			WHERE PROGRESS.SUBJECT like 'КГ') AS Средняя_по_КГ,
	(SELECT avg(PROGRESS.NOTE) FROM PROGRESS
			WHERE PROGRESS.SUBJECT like 'СУБД') AS Средняя_по_СУБД
	FROM PROGRESS


SELECT SUBJECT, NOTE FROM PROGRESS

SELECT SUBJECT, NOTE FROM PROGRESS
	WHERE NOTE >=ALL (SELECT NOTE FROM PROGRESS
						WHERE SUBJECT like 'ОАиП')

SELECT SUBJECT, NOTE FROM PROGRESS
	WHERE NOTE >=ANY (SELECT NOTE FROM PROGRESS
						WHERE SUBJECT like 'ОАиП')

SELECT STUDENT.NAME, STUDENT.BDAY FROM STUDENT
	WHERE BDAY IN(SELECT STUDENT.BDAY FROM STUDENT
						GROUP BY STUDENT.BDAY
						HAVING (count(STUDENT.BDAY) > 1))
						ORDER BY STUDENT.BDAY


USE Халалеенко_продажи
SELECT покупатель, телефон FROM покупатель
	WHERE покупатель IN(SELECT покупатель FROM покупатель
						WHERE покупатель like 'А%');