//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab5.WCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://schemas.datacontract.org/2004/07/lab5.WCF")]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double fField;
        
        private int kField;
        
        private string sField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double f
        {
            get
            {
                return this.fField;
            }
            set
            {
                this.fField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int k
        {
            get
            {
                return this.kField;
            }
            set
            {
                this.kField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string s
        {
            get
            {
                return this.sField;
            }
            set
            {
                this.sField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add", ReplyAction="http://tempuri.org/IService1/AddResponse")]
    int Add(int x, int y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add", ReplyAction="http://tempuri.org/IService1/AddResponse")]
    System.Threading.Tasks.Task<int> AddAsync(int x, int y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Concat", ReplyAction="http://tempuri.org/IService1/ConcatResponse")]
    string Concat(string s, double d);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Concat", ReplyAction="http://tempuri.org/IService1/ConcatResponse")]
    System.Threading.Tasks.Task<string> ConcatAsync(string s, double d);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sum", ReplyAction="http://tempuri.org/IService1/SumResponse")]
    lab5.WCF.A Sum(lab5.WCF.A a1, lab5.WCF.A a2);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sum", ReplyAction="http://tempuri.org/IService1/SumResponse")]
    System.Threading.Tasks.Task<lab5.WCF.A> SumAsync(lab5.WCF.A a1, lab5.WCF.A a2);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int Add(int x, int y)
    {
        return base.Channel.Add(x, y);
    }
    
    public System.Threading.Tasks.Task<int> AddAsync(int x, int y)
    {
        return base.Channel.AddAsync(x, y);
    }
    
    public string Concat(string s, double d)
    {
        return base.Channel.Concat(s, d);
    }
    
    public System.Threading.Tasks.Task<string> ConcatAsync(string s, double d)
    {
        return base.Channel.ConcatAsync(s, d);
    }
    
    public lab5.WCF.A Sum(lab5.WCF.A a1, lab5.WCF.A a2)
    {
        return base.Channel.Sum(a1, a2);
    }
    
    public System.Threading.Tasks.Task<lab5.WCF.A> SumAsync(lab5.WCF.A a1, lab5.WCF.A a2)
    {
        return base.Channel.SumAsync(a1, a2);
    }
}
