//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вклады
    {
        public int ID { get; set; }
        public Nullable<int> Код_клиента { get; set; }
        public Nullable<int> Номер_счёта { get; set; }
        public string Вид_вклада { get; set; }
        public string Сумма { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
    }
}
