//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public int ID { get; set; }
        public string ФИО { get; set; }
        public string Гражданство { get; set; }
        public string Адрес { get; set; }
        public string Фото { get; set; }
    
        public virtual Вклады Вклады { get; set; }
    }
}
