-- CreateTable
CREATE TABLE `authors` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `AUTHOR_NAME` VARCHAR(25) NOT NULL,

    UNIQUE INDEX `AUTHOR_NAME`(`AUTHOR_NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `book_author` (
    `BOOKID` INTEGER NOT NULL,
    `AUTHORID` INTEGER NOT NULL,
    `ID` INTEGER NOT NULL AUTO_INCREMENT,

    INDEX `AUTHORID`(`AUTHORID`),
    INDEX `BOOKID`(`BOOKID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `book_genre` (
    `BOOKID` INTEGER NOT NULL,
    `GENREID` INTEGER NOT NULL,
    `ID` INTEGER NOT NULL AUTO_INCREMENT,

    INDEX `BOOKID`(`BOOKID`),
    INDEX `GENREID`(`GENREID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `book_tag` (
    `BOOKID` INTEGER NOT NULL,
    `TAGID` INTEGER NOT NULL,
    `ID` INTEGER NOT NULL AUTO_INCREMENT,

    INDEX `BOOKID`(`BOOKID`),
    INDEX `TAGID`(`TAGID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `books` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `BOOK_NAME` TEXT NOT NULL,
    `BOOK_STATUS` BIT(1) NULL DEFAULT b'0',
    `BOOK_SERIES` TEXT NULL,
    `BOOK_DESCRIPTION` TEXT NULL,
    `CHAPTERS` INTEGER NULL,
    `DATA_RELEASE` INTEGER NULL,
    `DATA_ADD` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `feedback` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_USER` INTEGER NOT NULL,
    `ID_BOOK` INTEGER NOT NULL,
    `FEEDBACK` TEXT NULL,
    `RATING` FLOAT NOT NULL,
    `DATE` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `ID_BOOK`(`ID_BOOK`),
    INDEX `ID_USER`(`ID_USER`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `genre` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `GENRE_NAME` VARCHAR(50) NOT NULL,

    UNIQUE INDEX `GENRE_NAME`(`GENRE_NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tag` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TAG_NAME` VARCHAR(50) NOT NULL,

    UNIQUE INDEX `TAG_NAME`(`TAG_NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user_bookmarks` (
    `USERID` INTEGER NOT NULL,
    `BOOKID` INTEGER NOT NULL,
    `STATUS_READING` VARCHAR(25) NOT NULL,
    `PRESENCE` BIT(1) NOT NULL DEFAULT b'0',
    `DATA_READING` DATETIME(0) NULL,
    `DATA_ADD` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `MARKS` INTEGER NULL,
    `ID` INTEGER NOT NULL AUTO_INCREMENT,

    INDEX `BOOKID`(`BOOKID`),
    INDEX `USERID`(`USERID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `users` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(50) NOT NULL,
    `pass` VARCHAR(500) NOT NULL,
    `USER_NAME` VARCHAR(20) NOT NULL,
    `USER_INFO` TEXT NULL,
    `ACCESS_LEVEL` VARCHAR(20) NOT NULL,
    `DATA_CREATE` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `EMAIL`(`EMAIL`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `book_author` ADD CONSTRAINT `book_author_ibfk_1` FOREIGN KEY (`BOOKID`) REFERENCES `books`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `book_author` ADD CONSTRAINT `book_author_ibfk_2` FOREIGN KEY (`AUTHORID`) REFERENCES `authors`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `book_genre` ADD CONSTRAINT `book_genre_ibfk_1` FOREIGN KEY (`BOOKID`) REFERENCES `books`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `book_genre` ADD CONSTRAINT `book_genre_ibfk_2` FOREIGN KEY (`GENREID`) REFERENCES `genre`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `book_tag` ADD CONSTRAINT `book_tag_ibfk_1` FOREIGN KEY (`BOOKID`) REFERENCES `books`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `book_tag` ADD CONSTRAINT `book_tag_ibfk_2` FOREIGN KEY (`TAGID`) REFERENCES `tag`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `feedback` ADD CONSTRAINT `feedback_ibfk_1` FOREIGN KEY (`ID_USER`) REFERENCES `users`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `feedback` ADD CONSTRAINT `feedback_ibfk_2` FOREIGN KEY (`ID_BOOK`) REFERENCES `books`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `user_bookmarks` ADD CONSTRAINT `user_bookmarks_ibfk_1` FOREIGN KEY (`USERID`) REFERENCES `users`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `user_bookmarks` ADD CONSTRAINT `user_bookmarks_ibfk_2` FOREIGN KEY (`BOOKID`) REFERENCES `books`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
