//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Windows.Media.Imaging;
using WpfApp1.Annotations;
using WpfApp1.converter;

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;

    public partial class Products : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Comments = new HashSet<Comments>();
        }

        private BitmapImage _product_bitmap;
        private int _product_quantity;

        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public byte[] ProductImage { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> CategoryID { get; set; }

        public virtual Category _category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }

        public virtual Category Category
        {
            get => _category;
            set
            {
                _category = value;
                OnPropertyChanged("category");
            }
        }

        public string product_name
        {
            get => ProductName;
            set
            {
                ProductName = value;
                OnPropertyChanged("product_name");
            }
        }
        public double price
        {
            get => (double)Price;
            set
            {
                Price = (decimal)value;
                OnPropertyChanged("price");
            }
        }
        public int product_quantity
        {
            get => _product_quantity;
            set
            {
                _product_quantity = value;
                OnPropertyChanged("product_quantity");
            }
        }

        private byte[] product_image
        {
            get => ProductImage;
            set
            {
                ProductImage = value;
                OnPropertyChanged("product_image");
            }
        }

        private BitmapImage product_bitmap
        {
            get { return BinaryToBitmap.ByteToBitmapImage(ProductImage); }
            set
            {
                _product_bitmap = BinaryToBitmap.ByteToBitmapImage(ProductImage);
                OnPropertyChanged("product_bitmap");
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> order_details { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;

        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}

