//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab5
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://schemas.datacontract.org/2004/07/lab5")]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float FField;
        
        private int KField;
        
        private string SField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float F
        {
            get
            {
                return this.FField;
            }
            set
            {
                this.FField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int K
        {
            get
            {
                return this.KField;
            }
            set
            {
                this.KField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S
        {
            get
            {
                return this.SField;
            }
            set
            {
                this.SField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWCFSiplex")]
public interface IWCFSiplex
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSiplex/Add", ReplyAction="http://tempuri.org/IWCFSiplex/AddResponse")]
    int Add(int x, int y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSiplex/Add", ReplyAction="http://tempuri.org/IWCFSiplex/AddResponse")]
    System.Threading.Tasks.Task<int> AddAsync(int x, int y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSiplex/Concat", ReplyAction="http://tempuri.org/IWCFSiplex/ConcatResponse")]
    string Concat(string s, double d);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSiplex/Concat", ReplyAction="http://tempuri.org/IWCFSiplex/ConcatResponse")]
    System.Threading.Tasks.Task<string> ConcatAsync(string s, double d);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSiplex/Sum", ReplyAction="http://tempuri.org/IWCFSiplex/SumResponse")]
    lab5.A Sum(lab5.A a1, lab5.A a2);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSiplex/Sum", ReplyAction="http://tempuri.org/IWCFSiplex/SumResponse")]
    System.Threading.Tasks.Task<lab5.A> SumAsync(lab5.A a1, lab5.A a2);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWCFSiplexChannel : IWCFSiplex, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WCFSiplexClient : System.ServiceModel.ClientBase<IWCFSiplex>, IWCFSiplex
{
    
    public WCFSiplexClient()
    {
    }
    
    public WCFSiplexClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WCFSiplexClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFSiplexClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFSiplexClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int Add(int x, int y)
    {
        return base.Channel.Add(x, y);
    }
    
    public System.Threading.Tasks.Task<int> AddAsync(int x, int y)
    {
        return base.Channel.AddAsync(x, y);
    }
    
    public string Concat(string s, double d)
    {
        return base.Channel.Concat(s, d);
    }
    
    public System.Threading.Tasks.Task<string> ConcatAsync(string s, double d)
    {
        return base.Channel.ConcatAsync(s, d);
    }
    
    public lab5.A Sum(lab5.A a1, lab5.A a2)
    {
        return base.Channel.Sum(a1, a2);
    }
    
    public System.Threading.Tasks.Task<lab5.A> SumAsync(lab5.A a1, lab5.A a2)
    {
        return base.Channel.SumAsync(a1, a2);
    }
}
