// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMNrNH4w3GbO1HeyngKnn5CDmNd2Hzk6E',
    appId: '1:341276401350:web:ee07409511d66afda741c7',
    messagingSenderId: '341276401350',
    projectId: 'lab11-e4d16',
    authDomain: 'lab11-e4d16.firebaseapp.com',
    storageBucket: 'lab11-e4d16.firebasestorage.app',
    measurementId: 'G-RQZ6GLXD64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5iRTFlOQbb0HXgvTPrcXuMmt1R6zV3xQ',
    appId: '1:341276401350:android:eca757b3c34982c9a741c7',
    messagingSenderId: '341276401350',
    projectId: 'lab11-e4d16',
    storageBucket: 'lab11-e4d16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rmDl1FIBYYA3TPTZt5OQbvk5KbLJf-s',
    appId: '1:341276401350:ios:9a40d43dbf05dbc1a741c7',
    messagingSenderId: '341276401350',
    projectId: 'lab11-e4d16',
    storageBucket: 'lab11-e4d16.firebasestorage.app',
    iosBundleId: 'com.example.lab11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1rmDl1FIBYYA3TPTZt5OQbvk5KbLJf-s',
    appId: '1:341276401350:ios:9a40d43dbf05dbc1a741c7',
    messagingSenderId: '341276401350',
    projectId: 'lab11-e4d16',
    storageBucket: 'lab11-e4d16.firebasestorage.app',
    iosBundleId: 'com.example.lab11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMNrNH4w3GbO1HeyngKnn5CDmNd2Hzk6E',
    appId: '1:341276401350:web:928d22d704ff33e1a741c7',
    messagingSenderId: '341276401350',
    projectId: 'lab11-e4d16',
    authDomain: 'lab11-e4d16.firebaseapp.com',
    storageBucket: 'lab11-e4d16.firebasestorage.app',
    measurementId: 'G-CTRQ1S98XB',
  );

}