schema {
    query: Query,
    mutation: Mutation
}

type FACULTY {
    FACULTY: String!,
    FACULTY_NAME: String!
}

type PULPIT {
    PULPIT: String!,
    PULPIT_NAME: String!,
    FACULTY: String!
}

type TEACHER {
    TEACHER: String!,
    TEACHER_NAME: String!,
    PULPIT: String!
}

type SUBJECT {
    SUBJECT: String!,
    SUBJECT_NAME: String!,
    PULPIT: String!
}

type TBF {
    FACULTY: String!,
    TEACHERS:[TEACHER]
}

type SBF {
    PULPIT: String!,
    PULPIT_NAME: String!,
    FACULTY: String!,
    SUBJECTS:[SUBJECT]
}

type Query {
    getFaculties(FACULTY: String): [FACULTY],
    getTeachers(TEACHER: String): [TEACHER],
    getPulpits(PULPIT: String): [PULPIT],
    getSubjects(SUBJECT: String): [SUBJECT],

    getTeachersByFaculty(FACULTY: String!): [TBF],
    getSubjectsByFaculties(FACULTY: String!): [SBF]
}

type Mutation {
    setFaculty(FACULTY: String!, FACULTY_NAME: String!): FACULTY,
    setTeacher(TEACHER: String!, TEACHER_NAME: String!, PULPIT: String!): TEACHER,
    setPulpit(PULPIT: String!, PULPIT_NAME: String!, FACULTY: String!): PULPIT,
    setSubject(SUBJECT: String!, SUBJECT_NAME: String!, PULPIT: String!): SUBJECT,

    delFaculty(FACULTY: String!): Boolean,
    delTeacher(TEACHER: String!): Boolean,
    delPulpit(PULPIT: String!): Boolean,
    delSubject(SUBJECT: String!): Boolean
}