version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password   
      MYSQL_DATABASE: my_database          
      MYSQL_USER: user                     
      MYSQL_PASSWORD: user_password        
    ports:
      - "3306:3306"                       
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    restart: always     

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    restart: always

volumes:
  mysql_data:
